version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]

  web:
    build: .
    depends_on: [mongo]
    ports: ["80:3000"]
    environment:
      - MONGO_URL=mongodb://mongo:27017/sample
